// Package shellrc manages homelab-cli PATH blocks in shell rc files.
package shellrc

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strings"
)

// Entry is a shell rc snippet.
type Entry struct {
	Shell   string
	Content string
	Marker  string
}

// Shell identifies a shell rc file type.
type Shell string

// Supported shell rc targets.
const (
	Bash Shell = "bash"
	Zsh  Shell = "zsh"
	Fish Shell = "fish"
)

const (
	beginMarker = "# BEGIN homelab-cli managed block (do not edit — regenerated by `lab stack path refresh`)"
	endMarker   = "# END homelab-cli managed block"
)

// Detect returns shells to update based on $SHELL.
func Detect() ([]Shell, error) {
	shell := os.Getenv("SHELL")
	if shell == "" {
		if u, err := user.Current(); err == nil {
			shell = u.HomeDir
		}
	}
	shell = strings.ToLower(filepath.Base(shell))
	switch {
	case strings.Contains(shell, "zsh"):
		return []Shell{Zsh}, nil
	case strings.Contains(shell, "fish"):
		return []Shell{Fish}, nil
	default:
		return []Shell{Bash}, nil
	}
}

// RCPath returns the rc file path for a shell.
func RCPath(sh Shell) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	switch sh {
	case Bash:
		return filepath.Join(home, ".bashrc"), nil
	case Zsh:
		return filepath.Join(home, ".zshrc"), nil
	case Fish:
		return filepath.Join(home, ".config", "fish", "config.fish"), nil
	default:
		return "", fmt.Errorf("unsupported shell %q", sh)
	}
}

// UpdateBlock writes or replaces the managed block in the shell rc.
func UpdateBlock(sh Shell, entries []Entry) error {
	path, err := RCPath(sh)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	existing, _ := os.ReadFile(path)
	if len(existing) > 0 && !strings.Contains(string(existing), beginMarker) {
		backup := path + ".homelab-backup-" + fmt.Sprintf("%d", os.Getpid())
		_ = os.WriteFile(backup, existing, 0o600)
	}
	block := GenerateBlock(sh, entries)
	updated := replaceBlock(string(existing), block)
	return os.WriteFile(path, []byte(updated), 0o600)
}

// ReadBlock returns the managed block content.
func ReadBlock(sh Shell) (string, error) {
	path, err := RCPath(sh)
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	start := strings.Index(string(data), beginMarker)
	if start < 0 {
		return "", nil
	}
	end := strings.Index(string(data[start:]), endMarker)
	if end < 0 {
		return "", nil
	}
	return string(data[start : start+end+len(endMarker)]), nil
}

// RemoveBlock deletes the managed block from rc.
func RemoveBlock(sh Shell) error {
	path, err := RCPath(sh)
	if err != nil {
		return err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	updated := removeBlock(string(data))
	return os.WriteFile(path, []byte(updated), 0o600)
}

func replaceBlock(content, block string) string {
	start := strings.Index(content, beginMarker)
	if start < 0 {
		if content != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		return content + block + "\n"
	}
	endRel := strings.Index(content[start:], endMarker)
	if endRel < 0 {
		return content + "\n" + block + "\n"
	}
	end := start + endRel + len(endMarker)
	return content[:start] + block + content[end:]
}

func removeBlock(content string) string {
	start := strings.Index(content, beginMarker)
	if start < 0 {
		return content
	}
	endRel := strings.Index(content[start:], endMarker)
	if endRel < 0 {
		return content
	}
	end := start + endRel + len(endMarker)
	rest := strings.TrimPrefix(content[end:], "\n")
	return content[:start] + rest
}

// GenerateBlock builds shell-specific block content.
func GenerateBlock(sh Shell, entries []Entry) string {
	switch sh {
	case Fish:
		return generateFish(entries)
	default:
		return generateBashZsh(entries)
	}
}

func generateBashZsh(entries []Entry) string {
	var b strings.Builder
	b.WriteString(beginMarker)
	b.WriteByte('\n')
	for _, e := range entries {
		if e.Shell != "all" && e.Shell != "bash" && e.Shell != "zsh" {
			continue
		}
		if e.Marker != "" {
			fmt.Fprintf(&b, "# %s\n", e.Marker)
		}
		b.WriteString(e.Content)
		if !strings.HasSuffix(e.Content, "\n") {
			b.WriteByte('\n')
		}
	}
	b.WriteString(endMarker)
	return b.String()
}

func generateFish(entries []Entry) string {
	var b strings.Builder
	b.WriteString(beginMarker)
	b.WriteByte('\n')
	for _, e := range entries {
		if e.Shell != "all" && e.Shell != "fish" {
			continue
		}
		line := e.Content
		line = strings.ReplaceAll(line, "export ", "set -gx ")
		line = strings.ReplaceAll(line, "[ -f ", "test -f ")
		if e.Marker != "" {
			fmt.Fprintf(&b, "# %s\n", e.Marker)
		}
		b.WriteString(line)
		if !strings.HasSuffix(line, "\n") {
			b.WriteByte('\n')
		}
	}
	b.WriteString(endMarker)
	return b.String()
}
